---
# tasks file for tools_and_monitoring
# PMM
- name: install podman (like docker)
  when: (pmm_server_version != "" and docker == "") or podman != ""
  package:
    name: podman
    state: present
- name: install Percona Toolkit
  when: percona_toolkit_version != ""
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ os[dist]['percona_toolkit'].install_packages }}"

- name: install Perf
  when: perf != ""
  package:
    name: perf
    state: present

- name: install anydbver for docker/podman
  block:
    - name: install git
      package:
        name: git
        state: present
    - name: Enable EPEL
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'
      package:
        name: epel-release
        state: present
    - name: install jq
      package:
        name: jq
        state: present
    - name: fetch anydbver
      command:
        cmd: git clone -b docker-podman-k8s https://github.com/ihanick/anydbver.git /root/anydbver
        creates: /root/anydbver

- name: PMM Setup tasks
  when: install_only == ''
  include_tasks: setup.yaml
