---
# tasks file for kubernetes
- name: Install k3s, kubernetes distribution
  include_tasks: kubernetes_install.yaml
  when: (percona_k8s_op_pxc_version != '' or percona_k8s_op_psmdb_version != '' or zalando_pg_op_version != '' or percona_pg_op_version != '' or (k3s_url != '' and k3s_token != '') or k3s_version != '') and kube_config == ''

- name: helm tasks
  when: (k3s_url == '' and k3s_version != '') or kube_config != '' or k8s_minio != ''
  include_tasks: helm_install.yaml

- name: Install kubectl
  when: kube_config != ''
  block:
    - file: path=/root/.kube state=directory mode='0755'
    - copy:
        src: "{{playbook_dir}}/secret/{{kube_config}}"
        dest: /root/.kube/config
        mode: "0600"
        owner: root
        group: root
    - shell:
        warn: false
        cmd: curl -o /usr/bin/kubectl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl; chmod +x /usr/bin/kubectl
        creates: /usr/bin/kubectl

- name: Download yq
  when: percona_k8s_op_pxc_version != '' or percona_k8s_op_psmdb_version != '' or (install_only != '' and k3s_url == '' and k3s_version != '')
  get_url:
    url: 'https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64'
    dest: /usr/local/bin/yq
    mode: '0755'


- name: Install git for Percona Operator setup
  when: (percona_k8s_op_pxc_version != "" or percona_k8s_op_psmdb_version != "" or zalando_pg_op_version != "" or percona_pg_op_version != '')  or (install_only != '' and k3s_url == '' and k3s_version != '')
  package:
    name: git
    state: present

- name: bash completion
  package:
    name: bash-completion
    state: present

- name: kubectl bash completion
  when: (k3s_url == '' and k3s_version != '') or kube_config != ''
  shell:
    cmd: kubectl completion bash > /etc/bash_completion.d/kubectl
    creates: /etc/bash_completion.d/kubectl

- name: Setup Operator tasks
  when: install_only == ''
  include_tasks: setup_operators.yaml
